### ISSUE TITLE
optimization python3 generate.py

### ISSUE THREAD

**Issue by AndrewUshakov** [arsenyinfo/python-speedup-benchmark#1]
Здравствуйте, я на habrahabr - "readonly", поэтому комментирую здесь:

Я сильно удивился отставанию третьего питона в generate.py, поэтому решил посмотреть, в чем причина. Она оказалась несколько неожиданной - в этой версии питона случайные числа стали генерироваться медленнее, чем раньше. Решение и анализ ниже:

1) Если в generate.py поменять функцию generate_string на:

``` python
import numpy
al = numpy.array([a for a in ascii_letters])
def create_string(l=8):
    return u''.join(numpy.random.choice(al, l))
```

то python 3.5.1 (Windows, 64-bit) ускорится почти в 2 раза, а 2.7.11 - на 25%

2) Даже после такой "оптимизации" эта функция занимает примерно 65% от общего времени выполнения (судя по профилированию в pycharm). Еще 15% занимают суммарно radint и dumps(). 

3) В 3-м питоне строки юникодные, во втором - ascii, поэтому я бы перед всеми строками добавил префикс u, чтобы уравнять шансы, но эффект будет мал из-за пункта 2.

4) выражение ''.join(next(permutations(create_string(15), 12))) в той же generate.py, это просто первые 12 символов строки, возвращаемой create_string(15), т.е. то же самое, что и просто create_string(12). Но это уже совсем придирка.

С уважением, Андрей.

**Comment by arsenyinfo** [comment]
Андрей, спасибо! Учту в работе :- )
